# Generated by Django 4.0.4 on 2022-05-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_date_last_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_last',
        ),
    ]
