# Generated by Django 4.0.4 on 2022-05-03 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_remove_product_priority_order_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Developer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='developer',
        ),
    ]
