# Generated by Django 4.0.4 on 2022-05-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_customer_developer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='project',
        ),
    ]
